// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEtIF1dDjWBudm9n3gwHk1yjBIbX50Lmc',
    appId: '1:222563860975:web:e6a62d23c65b8639f7761a',
    messagingSenderId: '222563860975',
    projectId: 'cyber-cypher-healthcare',
    authDomain: 'cyber-cypher-healthcare.firebaseapp.com',
    storageBucket: 'cyber-cypher-healthcare.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNsq9xnRdZpWOBM4PeMtjoJMaFYs6ML0E',
    appId: '1:222563860975:android:de52f21e30cfdd61f7761a',
    messagingSenderId: '222563860975',
    projectId: 'cyber-cypher-healthcare',
    storageBucket: 'cyber-cypher-healthcare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjbkTdBNddB0NvMC8GxhpDn7PLzQOVw1k',
    appId: '1:222563860975:ios:2d4660c13080146bf7761a',
    messagingSenderId: '222563860975',
    projectId: 'cyber-cypher-healthcare',
    storageBucket: 'cyber-cypher-healthcare.appspot.com',
    iosBundleId: 'com.example.cyberCypherHealthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjbkTdBNddB0NvMC8GxhpDn7PLzQOVw1k',
    appId: '1:222563860975:ios:0224fa22a2975548f7761a',
    messagingSenderId: '222563860975',
    projectId: 'cyber-cypher-healthcare',
    storageBucket: 'cyber-cypher-healthcare.appspot.com',
    iosBundleId: 'com.example.cyberCypherHealthcare.RunnerTests',
  );
}
